### ISSUE TITLE
BUG in chess- Pawn promotion

### ISSUE THREAD

**Issue by w-miky-w** [Quackster/Havana#27] opened 2023-01-01 23:22 UTC
There's a bug in chess: the pawn promotion didn't work. A pawn when reaches the first row of the opponent’s side, had to become any other chess piece – Knight, Bishop, Rook, and even a Queen (not King though)

It was perfect if it's possible to add a string "Your turn" / "Opponent turn" and that both side (even those who choose black), play at the bottom of the board

![Screen](https://user-images.githubusercontent.com/121773583/210187320-bf0021f7-989c-480a-94ac-7bdfa1c03637.png)

**Comment by Quackster** [comment] 2023-01-15 22:37
I am using chesslib: https://github.com/bhlangonijr/chesslib

If you can figure out how I can use this library to do the expected behaviour, then I will make the changes, otherwise this open issue may go nowhere.

**Comment by Quackster** [comment] 2023-01-19 23:40
Merged here: https://github.com/Quackster/Havana/pull/30/commits/986621b73a64bd1e0893808dadca04cb9f091298

Will test and verify myself and then close this when I can confirm it works as intended, thank you!

**Comment by Quackster** [comment] 2023-01-21 06:46
Confirmed and working! 👍

![image](https://user-images.githubusercontent.com/1328523/213847494-0f39303d-42a5-4cc6-ba1a-c1f0289242f0.png)

**Closed by Quackster** 2023-01-21 06:46 UTC
Labels: bug
